bookshop_bookshop_homepage:
    pattern:  /
    defaults: { _controller: BookshopBookshopBundle:Page:index }
    
bookshop_bookshop_category:
    pattern:  /category
    defaults: { _controller: BookshopBookshopBundle:Page:productList }
    requirements: 
       _method:  GET
       id: \d+
       
bookshop_bookshop_search:
    pattern:  /search
    defaults: { _controller: BookshopBookshopBundle:Page:productList }
    requirements:
       _method:  GET
       id: \d+

bookshop_bookshop_productDetail:
    pattern:  /productDetail/{pid}
    defaults: { _controller: BookshopBookshopBundle:Page:productDetail }
    requirements:
       _method:  GET
       id: \d+
