parameters:
#    bookshop_bookshop.example.class: Bookshop\BookshopBundle\Example
     finder.class: Symfony\Component\Finder\Finder

services:
#    bookshop_bookshop.example:
#        class: %bookshop_bookshop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
   finder:
        class: "%finder.class%"
