<?php

namespace Bookshop\BookshopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CartItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartItemRepository extends EntityRepository
{
    public function getCartItemsForCart($cartId){
        $qd=$this->createQueryBuilder('c')
                ->select('c')
                ->where('c.cart= :cart_id')
                ->setParameter('cart_id',$cartId);
        return $qb->getQuery()
                  ->getResult();
        
    }
}
