<?php

namespace Bookshop\BookshopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository {

    public function getCartForUser($userId, $active = true) {
        $qd = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.user= :user_id')
                ->setParameter('user_id', $userId);
        if (false === is_null($active))
            $qd->andWhere('c.active = :active')
                    ->setParameter('active', 1);

        return $qd->getQuery()
                        ->getResult();
    }
  

}
